# -*- coding: utf-8 -*-
"""data visiualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_OWQhu7r9-iF0EJ6dPsRD503Z6YB4mU
"""

import numpy as np, matplotlib.pyplot as plt

plt.plot(x := np.linspace(0, 10, 100), x**2)
plt.title("Distance Over Time")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
plt.plot(x, x**2)

plt.title("Distance Over Time")
plt.xlabel("Time (s)")
plt.ylabel("Distance (m)")

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 1. Generate data
x = np.linspace(0, 10, 100)
y = x ** 2

# 2. Initialize the figure and axes (Object-Oriented Style)
fig, ax = plt.subplots(figsize=(8, 5))

# 3. Plot with styling
ax.plot(x, y,
        color='red',
        linestyle='--',
        marker='o',
        markevery=10,    # Prevents markers from being too crowded
        label=r'$y = x^2$')

# 4. Set labels and title using the 'set' methods
ax.set_title("Customized Line Plot", fontsize=14)
ax.set_xlabel("Time (seconds)")
ax.set_ylabel("Distance (meters)")

# 5. Final polish
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 1. Generate Data
# Creating 100 points between 0 and 10
time = np.linspace(0, 10, 100)
distance = time ** 2

# 2. Setup the Canvas (Object-Oriented Style)
# dpi=100 makes the image sharp; figsize sets the dimensions
fig, ax = plt.subplots(figsize=(8, 5), dpi=100)

# 3. Plotting with Style
# 'r--' is shorthand for red color and dashed line
ax.plot(time, distance, 'r--', linewidth=2, label=r'Path: $y = x^2$')

# 4. Adding Context (Labels & Title)
ax.set_title("Acceleration Analysis: Distance vs. Time", fontsize=14, pad=15)
ax.set_xlabel("Time (seconds)", fontsize=12)
ax.set_ylabel("Distance (meters)", fontsize=12)

# 5. Visual Refinement
ax.grid(True, linestyle=':', alpha=0.6)  # Subtle grid for readability
ax.legend(loc='upper left', frameon=True) # Legend to identify the line
plt.tight_layout()                       # Adjusts layout so nothing is cut off

# 6. Save and Display
# Saving with high resolution (300 DPI) for reports
plt.savefig('distance_plot.png', dpi=300, bbox_inches='tight')
plt.show()

import numpy as np, matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
fig, axs = plt.subplots(2, 2, figsize=(8, 6))

for i, ax in enumerate(axs.flat, 1):
    ax.plot(x, x**i, label=f'$x^{i}$')
    ax.set_title(f'Power {i}'); ax.legend()

plt.tight_layout(); plt.show()